require: rubocop-rspec

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

AllCops:
  NewCops: enable
