drop type if exists establishment;

create type establishment as enum (
	'Academy 16 to 19 sponsor led',
	'Academy 16-19 converter',
	'Academy alternative provision converter',
	'Academy alternative provision sponsor led',
	'Academy converter',
	'Academy secure 16 to 19',
	'Academy special converter',
	'Academy special sponsor led',
	'Academy sponsor led',
	'British schools overseas',
	'City technology college',
	'Community school',
	'Community special school',
	'Foundation school',
	'Foundation special school',
	'Free schools 16 to 19',
	'Free schools alternative provision',
	'Free schools special',
	'Free schools',
	'Further education',
	'Higher education institutions',
	'Institution funded by other government department',
	'Local authority nursery school',
	'Miscellaneous',
	'Non-maintained special school',
	'Offshore schools',
	'Online provider',
	'Other independent school',
	'Other independent special school',
	'Pupil referral unit',
	'Secure units',
	'Service children''s education',
	'Sixth form centres',
	'Special post 16 institution',
	'Studio schools',
	'University technical college',
	'Voluntary aided school',
	'Voluntary controlled school',
	'Welsh establishment'
);
